### ISSUE TITLE
Add Modal component

### ISSUE THREAD

**Issue by rotwurstesser** [liip-amboss/forge#14]
header
body/content/main
footer

**Comment by ingvijonasson** [comment]
The best article on accessible modal
https://bitsofco.de/accessible-modal-dialog/

**Comment by ingvijonasson** [comment]
@rotwurstesser this is a great accessibility exercise. Want to take it?

**Comment by rotwurstesser** [comment]
@ingvijonasson yessss!!!!!!

**Comment by ingvijonasson** [comment]
Would it be possible to have the possibility to set an hash so you could have a link to a page where the modal would be open?

**Comment by ingvijonasson** [comment]
resolved by #57
