### ISSUE TITLE
Add tailwind transition classes

### ISSUE THREAD

**Issue by ingvijonasson** [liip-amboss/forge#22]
Out of the box tailwind does not provide any classes for transition/animations.

**Comment by rotwurstesser** [comment]
While i love the idea and also really loved the way it was presented in the video [https://www.youtube.com/watch?v=J_7_mnFSLDg&t=904s] i would also like the idea of being able to generate them from config, i also think that Adam is working on transitions atm (see: https://twitter.com/adamwathan/status/1181638266996625410), so what would you think of adding a tailwind plugin like this: https://github.com/benface/tailwindcss-transitions 
i am not sure which way of making transitions work would be better for us but i would love to hear your ideas and thoughts on this @ingvijonasson @schtibe @JonasNiestroj

**Comment by rotwurstesser** [comment]
update: i have an open WIP MR and a branch where i gave it a try, if any of you want to play around with it feel free to check it out =) it's fun!

**Comment by rotwurstesser** [comment]
@ingvijonasson i have merged/added the transitions, if possible can we sit together and look at how we document things like this? it is not a real component but actually an "atom" that helps us build the components...

**Comment by ingvijonasson** [comment]
I think we should create a utility page in the documentation. Where we would simply link to tailwind page for now and add our additional classes. 

@rotwurstesser would you like to do that? 
... and document the transition classes?

**Comment by thetractor** [comment]
@ingvijonasson @rotwurstesser is this still in progress? do we still need this as it is now supported by Tailwind out of the box?

**Comment by ingvijonasson** [comment]
No we should drop this
