### ISSUE TITLE
Customize autoprefixer for css grid

### ISSUE THREAD

**Issue by ingvijonasson** [liip-amboss/forge#28]
Give example of how to use css grid so it will work for ie11.

https://github.com/postcss/autoprefixer#faq

**Comment by rotwurstesser** [comment]
@ingvijonasson i already found and adapted a tailwind plugin a little to generate grids for us, we can easily add some fallback things to it =)

**Comment by ingvijonasson** [comment]
OK cool, where can I see your changes?
@rotwurstesser 

The thing with css grid and autoprefixer is that it can handle some part of css grid but not everything. I would like to research and test that. Specially before intergrating with tailwind. Are you already aware of what autoprefixer can handle?

**Comment by JonasNiestroj** [comment]
@rotwurstesser Is this still a thing? I think everything is already handled by tailwind 1.2
